spring:
  datasource: 
    url: ${{ secrets.SPRING_DATASOURCE_URL }}
    username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
    password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true

payu:
  description: ${{ secrets.PAYU_DESCRIPTION }}
  merchant-pos-id: ${{ secrets.PAYU_MERCHANTPOSID }}
  second-key: ${{ secrets.PAYU_SECONDKEY }}
  client-id: ${{ secrets.PAYU_CLIENTID }}
  client-secret: ${{ secrets.PAYU_CLIENTSECRET }}
  url: https://secure.snd.payu.com/api/v2_1/orders
  authorization-url: https://secure.snd.payu.com/pl/standard/user/oauth/authorize
  continue-url: ${{ secrets.PAYU_CONTINUEURL }}
  notify-url: ${{ secrets.PAYU_NOTIFYURL }}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${{ secrets.MAIL_USERNAME }}
  password: ${{ secrets.MAIL_PASSWORD }}
  transport-protocol: smtp
  smtp-auth: true
  smtp-starttls-enable: true
  debug: true


