spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

payu:
  description: 
  merchant-pos-id: 
  second-key: 
  client-id: 
  url: https://secure.snd.payu.com/api/v2_1/orders
  authorization-url: https://secure.snd.payu.com/pl/standard/user/oauth/authorize
  client-secret: 
  continue-url: 
  notify-url: 

mail:
  host: smtp.gmail.com
  port: 587
  username: 
  password: 
  transport-protocol: smtp
  smtp-auth: true
  smtp-starttls-enable: true
  debug: true


